[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_program = "9F77hJsRRXs7vF9UDncZKth2r5wEPgcRkEfyoZDNQ3eK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "authority-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
